version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: oscarruiz05/w-challenge:latest
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
  db:
    image: postgres:17-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

volumes:
  postgres_data:
